apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-pv
  namespace: ownCloud
  labels:
    app: ownCloud
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s"
