apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  namespace: owncloud
  labels:
    app: owncloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      # initContainers:
      # - name: volume-dirs-init-cntr
      #   image: busybox:1.35
      #   command:
      #   - "/bin/mkdir"
      #   args:
      #   - "-p"
      #   - "/var/www/html/data"
      #   - "/var/www/html/apps"
      #   - "/var/www/html/config"
      containers:
      - name: owncloud
        image: owncloud
        volumeMounts:
        - mountPath: "/var/www/html/data"
          name: owncloud-pv
        - mountPath: "/var/www/html/apps"
          name: owncloud-pv-ssd-1g
        - mountPath: "/var/www/html/config"
          name: owncloud-pv-ssd-1g
      volumes:
      - name: owncloud-pv
        persistentVolumeClaim:
          claimName: owncloud-pvc
      - name: owncloud-pv-ssd-1g
        persistentVolumeClaim:
          claimName: owncloud-pvc-ssd-1g