apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  namespace: owncloud
  labels:
    app: owncloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    volumes:
    - name: owncloud-pv
      persistentVolumeClaim:
        claimName: owncloud-pvc
    spec:
      initContainers:
      - name: volume-dirs-init-cntr
        image: busybox:1.35
        command:
        - "/bin/mkdir"
        args:
        - "-p"
        - "/var/www/html/data"
        - "/var/www/html/apps"
        - "/var/www/html/config"
      containers:
      - name: owncloud
        image: owncloud
        volumeMounts:
        - mountPath: "/var/www/html/data"
          name: owncloud-pv
          subPath: /data
        - mountPath: "/var/www/html/apps"
          name: owncloud-pv
          subPath: /apps
        - mountPath: "/var/www/html/config"
          name: owncloud-pv
          subPath: /config
